### PR TITLE
Auto generate swagger json

### PR DESCRIPTION
**Pull request by fabriciovergal**
Not sure if you think this add too much complexity for this boilerplate, but this auto generation have been prove very handy to me :)

### CODE REVIEW

**Comment by fabriciovergal** [comment]
Just saw that 'class-validator-jsonschema' library is very unstable regarding generating models descriptions, better wait a ready-to-production version.

**Comment by dweber019** [comment]
@fabriciovergal thanks for your effort. We will track the progress of `class-validator-jsonschema` and consider the implementation as soon as production ready.

**Comment by stefan--** [comment]
@dweber019 do I understand it correctly that you manually have to update the `swagger.json`?

**Comment by dweber019** [comment]
@stefan-- yes, currently it's a manual task.

**Pull request closed without merging**
